# Generated by Django 2.1.5 on 2019-09-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateField(verbose_name='location date'),
        ),
    ]
