# Generated by Django 2.1.5 on 2019-09-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190911_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='traits',
            field=models.ManyToManyField(to='main_app.Trait'),
        ),
    ]
